config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects, shallow: true do
  resources :body_trackers, only: [:index] do
    collection do
      post 'defaults'
    end
  end

  resources :goals, except: [:show]

  resources :ingredients, only: [] do
    member do
      post 'adjust/:adjustment', controller: :meals, action: :adjust, as: :adjust
    end
  end
  resources :meals, except: [:show] do
    member do
      get 'edit_notes'
      patch 'update_notes'
      post 'toggle_eaten'
    end
    collection do
      post 'toggle_exposure'
    end
  end

  resources :measurement_routines, only: [:show, :edit] do
    resources :readouts, only: [:index]
    post 'toggle_exposure', controller: :readouts
  end
  # TODO: nest measurements inside routines?
  resources :measurements, except: [:show] do
    resource :readouts, only: [:edit, :update]
    member do
      get 'retake'
    end
    collection do
      get 'filter'
    end
  end

  resources :foods, except: [:show] do
    member do
      post 'toggle'
    end
    collection do
      get 'nutrients'
      post 'toggle_exposure'
      get 'filter'
      get 'autocomplete'
      post 'import'
    end
  end
  resources :sources, only: [:index, :create, :destroy]
  resources :quantities, except: [:show] do
    member do
      get 'new_child'
      post 'create_child'
      post 'move/:direction', action: :move, as: :move
    end
    collection do
      get 'parents'
      get 'filter'
    end
  end
  resources :units, only: [:index, :create, :destroy]
end

resources :goals, only: [] do
  resources :targets, param: :date, except: [:update] do
    member do
      get 'reapply'
    end
  end
  resource :targets, only: [:update]
  post 'toggle_exposure', controller: :targets
end
get 'subthresholds', controller: :targets, action: :subthresholds, as: :subthresholds

app/models/target.rb
class Target < ActiveRecord::Base
  belongs_to :goal, inverse_of: :targets, required: true
  has_one :project, through: :goal, inverse_of: :targets
  belongs_to :quantity, -> { where.not(domain: :target) }, inverse_of: :targets,
    required: true
  belongs_to :item, polymorphic: true, inverse_of: :targets
  has_many :thresholds, -> { joins(:quantity).order(:lft) },
    as: :registry, inverse_of: :target, dependent: :destroy, validate: true

  validates :thresholds, presence: true
  accepts_nested_attributes_for :thresholds, allow_destroy: true,
    reject_if: proc { |attrs| attrs['quantity_id'].blank? && attrs['id'].blank? }
  validate do
    quantities = thresholds.reject(&:marked_for_destruction?).map(&:quantity)
    ancestors = quantities.max_by(&:lft).self_and_ancestors
    errors.add(:thresholds, :count_mismatch) unless quantities.length == ancestors.length
    errors.add(:thresholds, :quantity_mismatch) unless quantities == ancestors
  end
  #validates :scope, inclusion: {in: [:ingredient, :meal, :day], if: -> { quantity&.diet? }}
  # FIXME: does not seem to work
  validates :effective_from, presence: {if: :is_binding?}, absence: {unless: :is_binding?}

  after_initialize do
    if new_record?
      # Target should be only instantiated through Goal, so :is_binding? will be available
      self.effective_from ||= Date.current if is_binding?
      if self.thresholds.empty?
        self.thresholds.new(quantity: self.goal.project.quantities.target.first)
      end
    end
  end

  delegate :is_binding?, to: :goal
  # NOTE: remove if not used in controller
  def arity
    thresholds.size
  end

  def to_s
    thresholds.last.quantity.description % thresholds.map do |t|
      [t.quantity.name.to_sym, "#{t.value} [#{t.unit.shortname}]"]
    end.to_h
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  layout 'body_tracking', except: :subthresholds
  menu_item :body_trackers
  helper :body_trackers

  include Finders

  before_action :find_goal_by_goal_id, only: [:index, :new, :create, :show, :edit, :update,
                                              :destroy, :reapply, :toggle_exposure]
  before_action :find_quantity_by_quantity_id, only: [:toggle_exposure, :subthresholds]
  before_action :authorize
  #before_action :set_view_params

  def index
    prepare_targets
  end

  def new
    target = @goal.targets.new
    @targets = [target]
    @effective_from = target.effective_from
  end

  def create
    @effective_from = params[:goal].delete(:effective_from).to_date
    params[:goal][:targets_attributes].each { |ta| ta[:effective_from] = @effective_from }

    if @goal.update(targets_params)
      count = @goal.targets.target.length
      if count > 0
        flash.now[:notice] = t('.success', count: count)
        prepare_targets
      else
        flash.now[:warning] = t('.success', count: 0)
        @targets = [@goal.targets.new]
        render :new
      end
    else
      @targets = @goal.targets.select(&:changed_for_autosave?)
        .each { |t| t.thresholds.new unless t.thresholds.present? }
      render :new
    end
  end

  def show
    # TODO: take into account nullified targets, after introduced
    @effective_from = params[:date].to_date
    targets = @goal.targets.joins(:quantity).where(
      "(quantity_id, effective_from) IN (?)",
      @goal.targets.select(:quantity_id, 'MAX(effective_from) as effective_from')
        .where("effective_from <= ?", @effective_from).group(:quantity_id)
    ).reorder('quantities.depth DESC')

    @quantities = {}
    targets.each do |t|
      unless @quantities.has_key?(t.quantity.parent)
        t.quantity.ancestors.each { |q| @quantities[q] = nil }
      end
      @quantities[t.quantity] = t
    end
  end

  def edit
    @effective_from = params[:date].to_date
    @targets = @goal.targets.joins(:quantity).where(effective_from: @effective_from)
      .order('quantities.lft' => :asc).to_a
  end

  def update
    @effective_from = params[:goal].delete(:effective_from).to_date
    params[:goal][:targets_attributes].each { |ta| ta[:effective_from] = @effective_from }

    if @goal.update(targets_params)
      count = @goal.targets.target.count { |t| t.previous_changes.present? }
      flash.now[:notice] = t('.success', count: count)
      prepare_targets
      render :index
    else
      @targets = @goal.targets.where(id: targets_params[:targets_attributes].pluck(:id))
      @targets += @goal.targets.target.select(&:changed_for_autosave?)
        .each { |t| t.thresholds.new unless t.thresholds.present? }
      render :edit
    end
  end

  def destroy
    @effective_from = params[:date].to_date
    @targets = @goal.targets.where(effective_from: @effective_from)
    count = @targets.destroy_all.length
    if @targets.all?(&:destroyed?)
      flash.now[:notice] = t('.success', count: count)
    else
      flash.now[:error] = t('.failure')
    end
  end

  def reapply
    @effective_from = ''
    targets = @goal.targets.where(effective_from: params[:date].to_date)
    @targets = targets.map do |t|
      duplicate = t.dup
      duplicate.thresholds = t.thresholds.map(&:dup)
      duplicate
    end
    render :new
  end

  def toggle_exposure
    @goal.exposures.toggle!(@quantity)
    prepare_targets
  end

  def subthresholds
    @quantities = @quantity.children
  end

  private

  def targets_params
    params.require(:goal).permit(
      targets_attributes:
        [
          :id,
          :quantity_id,
          :scope,
          :effective_from,
          :_destroy,
          thresholds_attributes: [
            :id,
            :quantity_id,
            :value,
            :unit_id,
            :_destroy
          ]
        ]
    )
  end

  def prepare_targets
    @quantities = @goal.quantities.includes(:formula)

    @targets_by_date = Hash.new { |h,k| h[k] = {} }
    @goal.targets.includes(:item, thresholds: [:quantity]).reject(&:new_record?)
      .each { |t| @targets_by_date[t.effective_from][t.quantity] = t }
  end

  def set_view_params
    @view_params = case params[:view]
                   when 'by_effective_from'
                     {view: :by_effective_from, effective_from: @effective_from}
                   when 'by_item_quantity'
                     {view: :by_item_quantity, item: nil, quantity: @quantity}
                   else
                     {view: :by_scope, scope: :all}
                   end
    #@view_params[:goal_id] = @goal.id if @goal
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
  def target_markup(date, quantity, target)
    content = "#{'&emsp;'*quantity.depth}#{quantity.name} #{target.to_s}"

    classes = []
    if date == target&.effective_from
      classes << 'bolded' if @goal.quantities.include?(quantity)
    else
      classes << 'dimmed'
    end

    content_tag(:span, content, {class: classes}, false)
  end

  def action_links(date)
    link_to(l(:button_reapply), reapply_goal_target_path(@goal, date, @view_params),
            {remote: true, class: "icon icon-reload"}) +
    link_to(l(:button_edit), edit_goal_target_path(@goal, date, @view_params),
            {remote: true, class: "icon icon-edit"}) +
    delete_link(goal_target_path(@goal, date), {remote: true, data: {}})
  end
end

app/views/targets/_contextual.html.erb
<% if User.current.allowed_to?(:manage_body_trackers, @project) %>
  <%= link_to t(".link_new_target"), new_goal_target_path(@goal, @view_params),
    {remote: true, class: 'icon icon-add'} %>
<% end %>

app/views/targets/_form.html.erb
<% if goal_f.object.is_binding? %>
  <p><%= goal_f.date_field :effective_from, value: @effective_from, required: true %></p>
<% end %>

<%= goal_f.fields_for :targets, @targets, index: '', child_index: '' do |target_f| %>
  <%= error_messages_for target_f.object %>

  <p class="target">
  <%= target_f.hidden_field :id %>
  <%= target_f.hidden_field :_destroy %>
  <em class="info"><%= t ".choose_quantity" %></em>
  <% required = target_f.object == @targets.first %>
  <%= target_f.select :quantity_id, quantity_options,
    {include_blank: true, required: required, label: (required ? :field_target : '')},
    onchange: "showQuantityPath(event);" %>

  <%= render partial: 'targets/thresholds_form',
    locals: {target_f: target_f,
             last_quantity: target_f.object.thresholds.last.quantity} %>

  <%= link_to t(".button_delete_target"), '#', class: 'icon icon-del',
    style: (@targets.many? ? '' : 'display:none'),
    onclick: 'deleteTarget(event); return false;' %>
  </p>
<% end %>

<p>
<%= link_to t(".button_new_target"), '#', class: 'icon icon-add',
  onclick: 'newTarget(event); return false;' %>
</p>

<%= javascript_tag do %>
  function showQuantityPath(event) {
    $(event.target).prevAll('em')
      .text($('option:selected', event.target).attr('data-path'));
  }
  $(document).ajaxComplete(function() {
    $('p.target').find('select:first').change();
  })

  function newTarget(event) {
    var form = $(event.target).closest('form');
    var target = form.find('p.target:visible:last');
    var new_target = target.clone().insertAfter(target);
    new_target.find('em').text('<%= t ".choose_quantity" %>');
    new_target.find('label:first').hide();
    new_target.find('input, select:first').val('');
    new_target.find('select.threshold:first').change();
    form.find('p.target:visible a.icon-del').show();
  }

  function deleteTarget(event) {
    var form = $(event.target).closest('form');
    var target = $(event.target).closest('p.target');
    if (target.find('input[id$=__id]').val()) {
      target.hide();
      target.find('input[id$=__destroy]').val('1');
    } else {
      target.remove();
    }
    form.find('p.target:visible:first label:first').show();
    if (form.find('p.target:visible').length <= 1) {
      form.find('p.target:visible a.icon-del').hide();
    }
  }

  function subthresholds(event) {
    $(event.target).nextUntil('a').hide();
    $(event.target).nextAll('input[id$=__destroy]').val('true');

    if ($(event.target).val() != "") {
      var threshold_value = $(event.target).nextUntil('select.threshold, a');
      if (threshold_value.length == 0) {
        template = $(event.target).closest('p.target').find('select.threshold:first')
          .nextUntil('select.threshold, a').not('input[type=hidden]');
        threshold_value = template.clone().insertAfter($(event.target)).before(" ");
      }
      threshold_value.show();
      threshold_value.filter('input[id$=__destroy]').val('false');

      $.ajax({
        url: '<%= subthresholds_path %>',
        data: {'quantity_id' : $(event.target).val()},
        dataType: 'html',
        success: function(data) {
          if (data) {
            var threshold_quantity = $(event.target).nextAll('select.threshold:first');
            if (threshold_quantity.length == 0) {
              threshold_quantity = $(event.target).clone()
                .insertAfter(threshold_value.last()).before(" ");
            }
            threshold_quantity.show().empty().append(data);
          }
        }
      });
    }
  }
<% end %>

app/views/targets/_index.html.erb
<% if @targets_by_date.any? %>
  <%= render partial: 'targets/options' %>

  <% formulas = @quantities.collect(&:formula) %>
  <%= error_messages_for *formulas %>

  <table id="targets" class="list odd-even">
    <%= quantities_table_header @quantities, :field_effective_from do |quantity_id|
      goal_toggle_exposure_path(@goal, quantity_id: quantity_id)
    end %>

    <tbody>
      <% @targets_by_date.each do |date, targets| %>
        <tr id="date-<%= date %>" class="date <%= cycle('odd', 'even') %>">
          <td class="topleft unwrappable">
            <%= link_to(format_date(date), goal_target_path(@goal, date),
                        {remote: true, class: 'icon icon-arrow-right'}) %>
          </td>
          <% @quantities.each do |q| %>
            <td class="right unwrappable"><%= raw targets[q].to_s %></td>
          <% end %>
          <td class="right shrunk unwrappable"><%= action_links(date) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/targets/_new_form.html.erb
<h2><%= t ".heading_new_target" %></h2>

<%= labelled_form_for @goal, url: goal_targets_path(@goal), method: :post, remote: true,
  html: {id: 'new-target-form', name: 'new-target-form'} do |goal_f| %>

  <div class="box tabular">
    <%= render partial: 'targets/form', locals: {goal_f: goal_f} %>
  </div>

  <div class="tabular">
    <p>
      <%= submit_tag l(:button_create) %>
      <%= link_to l(:button_cancel), "#",
        onclick: "$('#new-target').empty(); return false;" %>
    </p>
  </div>
<% end %>
<hr>

app/views/targets/_options.html.erb
<fieldset id="options" class="collapsible">
  <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
  <div>
    <%= form_tag goal_toggle_exposure_path(@goal, @view_params),
      id: 'toggle-exposure-form', name: 'toggle-exposure-form',
      method: :post, remote: true do %>

      <table>
        <tr>
          <td style="width:100%"></td>
          <td><%= select_tag 'quantity_id',
            toggle_exposure_options(@goal.quantities) %></td>
          <td><%= submit_tag l(:button_add) %></td>
        </tr>
      </table>
    <% end %>
  </div>
</fieldset>

app/views/targets/_show.html.erb
<tr class="details">
  <td class="topleft">
    <%= link_to l(:button_close), "#", {class: 'icon icon-close',
          onclick: '$(this).closest("tr").nextUntil("tr.date", "tr:not(.details)").show()
            .addBack().first().remove(); return false;'} %>
  </td>
  <% content = @quantities.keys.sort_by(&:lft).inject('') do |output, q| %>
    <% raw "#{output}#{target_markup(@effective_from, q, @quantities[q])}\n" %>
  <% end %>
  <td class="topleft" colspan="<%= @goal.exposures.length + 1 %>"
      style="white-space:pre-line;"><%= content %></td>
</tr>

app/views/targets/_thresholds_form.html.erb
<% target_f.object.thresholds.new unless last_quantity.leaf? %>
<%= target_f.fields_for :thresholds, index: '', child_index: '' do |threshold_f| %>
  <% threshold_q = threshold_f.object.quantity %>
  <% parent_id = threshold_q.nil? ? last_quantity.id : threshold_q.parent_id  %>
  <%= threshold_f.collection_select :quantity_id,
                                    @project.quantities.target.children_of(parent_id),
                                    :id, :name,
    {include_blank: parent_id.nil? ? false : '.', required: true, no_label: true},
    {autocomplete: 'off', onchange: 'subthresholds(event); return false;',
     class: 'threshold'} %>

  <% unless threshold_q.nil? %>
    <%= threshold_f.hidden_field :id %>
    <%= threshold_f.hidden_field :_destroy %>
    <%= threshold_f.number_field :value, {size: 8, step: :any, no_label: true} %>
    <%= threshold_f.collection_select :unit_id, @project.units, :id, :shortname,
                                      {no_label: true} %>
  <% end %>
<% end %>

app/views/targets/create.js.erb
$('#new-target').empty();
<%# case @view_params[:view] %>
  <%# when :by_date %>
//    $('#targets').html('<%#= j render partial: 'targets/by_effective_date' %>');
  <%# else %>
    $('#targets').html('<%= j render partial: 'targets/index' %>');
<%# end %>

app/views/targets/destroy.js.erb
<% if @targets.all?(&:destroyed?) %>
  $('tr[id=date-<%= @effective_from %>]').nextUntil('tr.date').addBack().remove();
<% end %>

app/views/targets/index.html.erb
<div class="contextual">
  <%= render partial: 'targets/contextual' %>
</div>

<div id="new-target">
</div>

<%= title [t("goals.index.heading"), project_goals_path(@project)], @goal.name %>
<% if @goal.description? %>
  <p class="subtitle" style='white-space: pre-wrap;'><%= @goal.description %></p>
<% end %>
<div id='targets'>
  <%= render partial: 'targets/index' %>
</div>

app/views/targets/new.js.erb
$('#new-target').html('<%= j render partial: 'targets/new_form' %>');

app/views/targets/show.js.erb
var row = $('tr[id=date-<%= @effective_from %>]');
row.nextUntil('tr.date').remove('tr.details').hide();
row.after('<%= j render partial: 'targets/show' %>').next()
  .addClass(row.hasClass('even') ? 'even' : 'odd');

app/views/targets/subthresholds.html.erb
<%= options_for_select [['.', nil]] unless @quantities.empty? -%>
<%= options_from_collection_for_select(@quantities, :id, :name) -%>

app/views/targets/toggle_exposure.js.erb
$('#targets').html('<%= j render partial: 'targets/index' %>');