config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects, shallow: true do
  resources :body_trackers, only: [:index] do
    collection do
      post 'defaults'
    end
  end

  resources :goals, except: [:show]

  resources :ingredients, only: [] do
    member do
      post 'adjust/:adjustment', controller: :meals, action: :adjust, as: :adjust
    end
  end
  resources :meals, except: [:show] do
    member do
      get 'edit_notes'
      patch 'update_notes'
      post 'toggle_eaten'
    end
    collection do
      post 'toggle_exposure'
    end
  end

  resources :measurement_routines, only: [:show, :edit] do
    resources :readouts, only: [:index]
    post 'toggle_exposure', controller: :readouts
  end
  # TODO: nest measurements inside routines?
  resources :measurements, except: [:show] do
    resource :readouts, only: [:edit, :update]
    member do
      get 'retake'
    end
    collection do
      get 'filter'
    end
  end

  resources :foods, except: [:show] do
    member do
      post 'toggle'
    end
    collection do
      get 'nutrients'
      post 'toggle_exposure'
      get 'filter'
      get 'autocomplete'
      post 'import'
    end
  end
  resources :sources, only: [:index, :create, :destroy]
  resources :quantities, except: [:show] do
    member do
      get 'new_child'
      post 'create_child'
      post 'move/:direction', action: :move, as: :move
    end
    collection do
      get 'parents'
      get 'filter'
    end
  end
  resources :units, only: [:index, :create, :destroy]
end

resources :goals, only: [] do
  resources :targets, param: :date, except: [:update] do
    member do
      get 'reapply'
    end
  end
  resource :targets, only: [:update]
  post 'toggle_exposure', controller: :targets
end
get 'subthresholds', controller: :targets, action: :subthresholds, as: :subthresholds

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :project, required: true

  has_many :ingredients, as: :composition, inverse_of: :composition, dependent: :destroy,
    validate: true
  has_many :foods, through: :ingredients
  validates :ingredients, presence: true
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: proc { |attrs|
    attrs['food_id'].blank? && attrs['amount'].blank?
  }
  # Ingredient food_id + part_of_id uniqueness validation. Cannot be effectively
  # checked on Ingredient model level.
  validate do
    ingredients = self.ingredients.reject { |i| i.marked_for_destruction? }
      .map { |i| [i.food_id, i.part_of_id] }
    if ingredients.length != ingredients.uniq.length
      errors.add(:ingredients, :duplicated_ingredient)
    end
  end

  def eaten_at
    self[:eaten_at].getlocal if self[:eaten_at]
  end
  alias_attribute :completed_at, :eaten_at

  def eaten_at_date
    self.eaten_at
  end
  def eaten_at_date=(value)
    self.eaten_at = Time.parse(value, self.eaten_at)
  end

  def eaten_at_time
    self.eaten_at
  end
  def eaten_at_time=(value)
    self.eaten_at = Time.parse(value, self.eaten_at)
  end

  def toggle_eaten!
    update(eaten_at: self.eaten_at ? nil : DateTime.current)
  end

  def display_date
    self.eaten_at ? self.eaten_at.to_date : Date.current
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  layout 'body_tracking'
  menu_item :body_trackers
  helper :body_trackers

  include Finders

  before_action :find_project_by_project_id, only: [:index, :new, :create]
  before_action :find_quantity_by_quantity_id, only: [:toggle_exposure]
  before_action :find_meal, only: [:edit, :update, :destroy, :edit_notes, :update_notes,
                                   :toggle_eaten]
  before_action :find_ingredient, only: [:adjust]
  before_action :authorize

  def index
    prepare_meals
  end

  def new
    @meal = @project.meals.new
    @meal.ingredients.new
  end

  def create
    @meal = @project.meals.new(meal_params)
    if @meal.save
      flash.now[:notice] = 'Created new meal'
      prepare_meals
    else
      @meal.ingredients.new if @meal.ingredients.empty?
      render :new
    end
  end

  def edit
  end

  def update
    if @meal.update(meal_params)
      flash.now[:notice] = 'Updated meal'
      prepare_meals
      render :index
    else
      render :edit
    end
  end

  def destroy
    flash.now[:notice] = 'Deleted meal' if @meal.destroy
  end

  def edit_notes
  end

  def update_notes
    @meal.update(params.require(:meal).permit(:notes))
  end

  def toggle_eaten
    @meal.toggle_eaten!
    prepare_meals
  end

  def toggle_exposure
    @project.meal_exposures.toggle!(@quantity)
    prepare_meals
  end

  def adjust
    amount = params[:adjustment].to_i
    @ingredient.amount += amount if @ingredient.amount > -amount
    @ingredient.save

    prepare_meals
    @meal = @ingredient.composition
    @date = @meal.display_date
    @meal_index = @meals_by_date[@date].index(@meal)
  end

  private

  def meal_params
    params.require(:meal).permit(
      :notes,
      ingredients_attributes:
      [
        :id,
        :food_id,
        :amount,
        :_destroy
      ]
    )
  end

  def prepare_meals
    @meals_by_date = @project.meals.reject(&:new_record?)
      .sort_by { |m| m.eaten_at || m.created_at }.group_by(&:display_date)

    return if @meals_by_date.empty?

    @quantities = @project.meal_quantities.includes(:formula)
    @ingredients = @project.meal_ingredients.compute_quantities(@quantities) do |q, items|
      Hash.new { |h,k| k.composition } if q == Meal
    end

    @amount_mfu_unit = @ingredients
      .each_with_object(Hash.new(0)) { |(i, qv), h| h[i.food.ref_unit] += 1 }
      .max_by(&:last).first

    @ingredient_summary = Hash.new { |h,k| h[k] = Hash.new(BigDecimal(0)) }
    @quantities.each do |q|
      @ingredient_summary[:mfu_unit][q] = @ingredients
        .each_with_object(Hash.new(0)) { |(i, qv), h| h[qv[q].last] += 1 if qv[q] }
        .max_by(&:last).try(&:first)

      max_value = @ingredients.map { |i, qv| qv[q].try(&:first) || BigDecimal(0) }.max
      @ingredient_summary[:precision][q] = [3 - max_value.exponent, 0].max
    end

    # TODO: summing up ingredients should take units into account
    @ingredients.each do |i, qv|
      meal = i.composition
      qv.compact.each do |q, (a, u)|
        @ingredient_summary[meal][q] += a
        @ingredient_summary[meal.display_date][q] += a
      end
    end
  end
end

app/helpers/meals_helper.rb
module MealsHelper
  def meal_links(m)
    link_to(l(:button_edit), edit_meal_path(m),
            {remote: true, class: "icon icon-edit"}) +
    delete_link(meal_path(m), {remote: true, data: {}})
  end

  def adjustment_buttons(i)
    {'- -' => -10, '-' => -1, '+' => 1, '++' => 10}.map do |text, value|
      link_to text, adjust_ingredient_path(i, adjustment: value),
        {remote: true, method: :post, class: "button #{value>0 ? 'green' : 'red'}"}
    end.reduce(&:+)
  end

  def notes(m)
    content_tag(:span, m.notes)
  end
end

app/views/meals/_contextual.html.erb
<% if User.current.allowed_to?(:manage_body_trackers, @project) %>
  <%= link_to t(".link_new_meal"), new_project_meal_path(@project),
    {remote: true, class: 'icon icon-add'} %>
<% end %>

app/views/meals/_edit_form.html.erb
<%= labelled_form_for @meal,
  url: meal_path(@meal),
  method: :patch, remote: true,
  html: {id: 'edit-meal-form', name: 'edit-meal-form'} do |f| %>

  <%= render partial: 'meals/form', locals: {f: f} %>

  <div class="tabular">
    <p>
      <%= submit_tag l(:button_save) %>
      <%= link_to l(:button_cancel), "#",
        onclick: '$(this).closest("tr").remove(); return false;' %>
    </p>
  </div>
<% end %>

app/views/meals/_form.html.erb
<%= error_messages_for @meal %>

<div class="box">
  <div class="tabular">
    <div class="splitcontent">
      <div class="splitcontentleft">
        <p>
        <%= f.date_field :eaten_at_date, required: false %>
        <%= f.time_field :eaten_at_time, value: format_time(@meal.eaten_at),
          required: false, label: '' %>
        </p>
      </div>
      <div class="splitcontentright">
        <p><%= f.text_field :notes, required: false, style: "width: 95%;" %></p>
      </div>
    </div>

    <% @meal.ingredients.each_with_index do |i, index| %>
      <table style="width:95%;">
        <%= f.fields_for 'ingredients_attributes', i, index: '' do |ff| %>
          <tr class="ingredient">
            <td style="width:90%;">
              <p>
              <%= ff.hidden_field :id %>
              <%= ff.hidden_field :food_id, {class: "autocomplete-value"} %>
              <%= label_tag :food_name do %>
                <%= index > 0 ? '' : t(:field_ingredients) %><span class="required"> *</span>
              <% end %>
              <%= text_field_tag :food_name, (i.food.name if i.food),
                {class: "autocomplete autocomplete-label", style: "width: 80%;"} %>
              <%= ff.number_field :amount, {style: "width: 8%", step: :any, label: ''} %>
              <%= i.food.ref_unit.shortname if i.food %>
              <%= ff.hidden_field :_destroy %>
              </p>
            </td>
            <td style="width:10%;">
              <%= link_to t(".button_delete_ingredient"), '#',
                class: 'icon icon-del',
                style: (@meal.ingredients.length > 1 ? "" : "display:none"),
                onclick: "deleteIngredient(); return false;" %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
    <p>
    <%= link_to t(".button_new_ingredient"), '#', class: 'icon icon-add',
      onclick: 'newIngredient(); return false;' %>
    </p>
  </div>
</div>

<%= javascript_tag do %>
  function autocompleteFood($row) {
    $row.find('.autocomplete-label').autocomplete({
      source: '<%= j autocomplete_project_foods_path(@project) %>',
      minLength: 2,
      position: {collision: 'flipfit'},
      search: function(event){
        $(event.target).addClass('ajax-loading');
      },
      response: function(event){
        $(event.target).removeClass('ajax-loading');
      },
      select: function(event, ui) {
        $(event.target).val(ui.item.label);
        $(event.target).siblings('.autocomplete-value').val(ui.item.value)
        return false;
      },
      focus: function(event, ui) {
        $(event.target).val(ui.item.label);
        return false;
      }
    });
  }
  autocompleteFood($('tr.ingredient:visible'));

  function newIngredient() {
    var form = $(event.target).closest('form');
    var row = form.find('tr.ingredient:visible:last');
    var new_row = row.clone().insertAfter(row);
    new_row.find('input:not([id$=__destroy])').val('');
    new_row.find('label:first').hide();
    form.find('tr.ingredient:visible a.icon-del').show();
    autocompleteFood(new_row);
    new_row.find('input:visible:first').focus();
  }

  function deleteIngredient() {
    var form = $(event.target).closest('form');
    var row = $(event.target).closest('tr.ingredient');
    if (row.find('input[id$=__id]').val()) {
      row.hide();
      row.find('input[id$=__destroy]').val('1');
    } else {
      row.remove();
    }
    form.find('tr.ingredient:visible:first label:first').show();
    if (form.find('tr.ingredient:visible').length <= 1) {
      form.find('tr.ingredient:visible a.icon-del').hide();
    }
  }
<% end %>

app/views/meals/_index.html.erb
<% if @meals_by_date.any? %>
  <%= render partial: 'meals/options' %>

  <% formulas = @quantities.map { |q| q.formula } %>
  <% formulas.unshift(@filter_q.formula) if @filter_q %>
  <%= error_messages_for *formulas %>

  <table id="meals" class="list odd-even">
    <tbody>
      <% total_width = 4 + @quantities.length %>
      <% header = quantities_table_header(@quantities) %>
      <% @meals_by_date.reverse_each do |date, meals| %>
        <% header.each_with_index do |row, i| %>
          <tr class="header">
            <% if i == 0 %>
              <td colspan="2" rowspan="<%= 1 + header.length %>"
                  style="width:<%= 3 * 100/total_width %>%; border: none;"></td>
              <td class="quantityhead" rowspan="<%= header.length %>"
                  style="width:<%= 100/total_width %>%;"><%= l(:field_amount) %></td>
            <% end %>

            <% row.each do |q, span| %>
              <td class="<%= span ? 'quantityhead' : 'quantityheadempty' %>"
                  <%= "colspan=#{span}" if span && span > 0 %>
                  <%= "rowspan=#{-span}" if span && span < 0 %>
                  style="width: <%= (span && span > 0 ? span : 1) * 100/total_width %>%;"
                  title="<%= q.description %>">
                <%= q.name if span %>
              </td>
            <% end %>

            <% if i == 0 %>
              <td rowspan="<%= 1 + header.length %>"
                  style="width:<%= 100/total_width %>%; border: none;"></td>
            <% end %>
          </tr>
        <% end %>

        <tr class="header">
          <td class="quantityhead"><%= "[#{@amount_mfu_unit.shortname}]" %></td>
          <% @quantities.each do |q| %>
            <td class="quantityhead">
              <%= "[#{@ingredient_summary[:mfu_unit][q].try(&:shortname) || '-'}]" %>
            </td>
          <% end %>
        </tr>

        <%= render partial: 'meals/show_date', locals: {date: date} %>

        <% meals.each_with_index do |m, index| %>
          <%= render partial: 'meals/show', locals: {m: m, index: index} %>
          <% m.ingredients.each do |i| %>
            <%= render partial: 'meals/show_ingredient', locals: {i: i} %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/meals/_new_form.html.erb
<h2><%= t ".heading_new_meal" %></h2>

<%= labelled_form_for @meal,
  url: project_meals_path(@project),
  remote: true,
  html: {id: 'new-meal-form', name: 'new-meal-form'} do |f| %>

  <%= render partial: 'meals/form', locals: {f: f} %>

  <div class="tabular">
    <p>
      <%= submit_tag l(:button_create) %>
      <%= link_to l(:button_cancel), "#",
        onclick: '$("#new-meal").empty(); return false;' %>
    </p>
  </div>
<% end %>
<hr>

app/views/meals/_options.html.erb
<fieldset id="options" class="collapsible">
  <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
  <div>
    <%= form_tag toggle_exposure_project_meals_path(@project),
      id: 'toggle-exposure-form', name: 'toggle-exposure-form',
      method: :post, remote: true do %>

      <table>
        <tr>
          <td style="width:100%"></td>
          <td><%= select_tag 'quantity_id',
            toggle_exposure_options(@project.meal_quantities, :diet) %></td>
          <td><%= submit_tag l(:button_toggle) %></td>
        </tr>
      </table>
    <% end %>
  </div>
</fieldset>

app/views/meals/_show.html.erb
<tr id="meal-<%= m.id %>" class="primary meal project idnt idnt-1"
    style="background-color: #d0e0e3;">
  <td class="topleft unwrappable" style="border-right: none;">
    <b><%= "#{t '.label_meal'} ##{index+1}" %></b>
    <% if m.eaten_at %>
      <%= " at #{m.eaten_at.strftime('%R')}" %>
      <%= link_to '', toggle_eaten_meal_path(m),
        {remote: true, method: :post, class: "icon icon-close"} %>
    <% else %>
      <%= link_to l(:button_eat), toggle_eaten_meal_path(m),
        {remote: true, method: :post, class: "icon icon-time"} %>
    <% end %>
  </td>

  <td id="notes-links-<%= m.id %>" class="unwrappable"
      style="text-align: left; border-left: none; border-right: none; width: 1%;">
    <%= link_to l(:button_cancel), '', class: 'icon icon-cancel', style: 'display: none;',
      onclick: "$(event.target).closest('tr').find('form').remove();
                $('td[id=notes-#{m.id}]').contents().show();
                $('td[id=notes-links-#{m.id}] a').toggle();
                return false;" %>

    <%= link_to l(:button_save), '', class: 'icon icon-save', style: 'display: none;',
      onclick: "$(event.target).closest('tr').find('form').submit(); return false;" %>

    <%= link_to l(:button_notes), edit_notes_meal_path(m), remote: true,
      class: "icon icon-wiki-page" %>
  </td>

<% if false %>
  <td id="notes-<%= m.id %>" class="notes unwrappable" colspan="<%= @quantities.length + 1 %>"
      style="text-align: left; border-left: none;">
    <%= notes(m) %>
  </td>
<% end %>

  <td class="right ellipsible" style="border-left: none;"></td>
  <% @quantities.each do |q| %>
    <td class="right ellipsible">
      <%= format_amount(@ingredient_summary[m][q], @ingredient_summary[:precision][q]) %>
    </td>
  <% end %>

  <td class="right shrunk unwrappable"><%= meal_links(m) %></td>
</tr>

app/views/meals/create.js.erb
$('#new-meal').empty();
$('#meals').html('<%= j render partial: 'meals/index' %>');

app/views/meals/edit.js.erb
$('tr[id=meal-<%= @meal.id %>]').nextUntil('tr.primary, tr.date', ':not(.ingredient)').remove();
var columns = $('table > tbody > tr.ingredient > td').length;
$('tr[id=meal-<%= @meal.id %>]').nextUntil('tr.primary, tr.date').addBack().last().after(
  '<tr><td class="form" colspan="'+columns+'"><div id="edit-meal">' +
  '<%= j render partial: 'meals/edit_form' %>' +
  '</div></td></tr>'
);

app/views/meals/edit_notes.js.erb
var notes = $('td[id=notes-<%= @meal.id %>]');
notes.contents().hide();
notes.append('<%= j render partial: 'meals/edit_notes_form' %>');
notes.find('input[type=text]').focus();
$('td[id=notes-links-<%= @meal.id %>] a').toggle();

app/views/meals/index.html.erb
<div class="contextual">
  <%= render partial: 'meals/contextual' %>
</div>

<div id="new-meal">
</div>

<%= title t(".heading") %>
<div id='meals'>
  <%= render partial: 'meals/index' %>
</div>

app/views/meals/index.js.erb
$('#meals').html('<%= j render partial: 'meals/index' %>');

app/views/meals/toggle_exposure.js.erb
$('#meals').html('<%= j render partial: 'meals/index' %>');

app/views/meals/update_notes.js.erb
$('td[id=notes-<%= @meal.id %>]').html('<%= j notes(@meal) %>');
$('td[id=notes-links-<%= @meal.id %>] a').toggle();