config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects, shallow: true do
  resources :body_trackers, only: [:index] do
    collection do
      post 'defaults'
    end
  end

  resources :goals, except: [:show]

  resources :ingredients, only: [] do
    member do
      post 'adjust/:adjustment', controller: :meals, action: :adjust, as: :adjust
    end
  end
  resources :meals, except: [:show] do
    member do
      get 'edit_notes'
      patch 'update_notes'
      post 'toggle_eaten'
    end
    collection do
      post 'toggle_exposure'
    end
  end

  resources :measurement_routines, only: [:show, :edit] do
    resources :readouts, only: [:index]
    post 'toggle_exposure', controller: :readouts
  end
  # TODO: nest measurements inside routines?
  resources :measurements, except: [:show] do
    resource :readouts, only: [:edit, :update]
    member do
      get 'retake'
    end
    collection do
      get 'filter'
    end
  end

  resources :foods, except: [:show] do
    member do
      post 'toggle'
    end
    collection do
      get 'nutrients'
      post 'toggle_exposure'
      get 'filter'
      get 'autocomplete'
      post 'import'
    end
  end
  resources :sources, only: [:index, :create, :destroy]
  resources :quantities, except: [:show] do
    member do
      get 'new_child'
      post 'create_child'
      post 'move/:direction', action: :move, as: :move
    end
    collection do
      get 'parents'
      get 'filter'
    end
  end
  resources :units, only: [:index, :create, :destroy]
end

resources :goals, only: [] do
  resources :targets, param: :date, except: [:update] do
    member do
      get 'reapply'
    end
  end
  resource :targets, only: [:update]
  post 'toggle_exposure', controller: :targets
end
get 'subthresholds', controller: :targets, action: :subthresholds, as: :subthresholds

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :project, required: true
  has_many :targets, -> { order effective_from: :desc }, inverse_of: :goal,
    dependent: :destroy, extend: BodyTracking::ItemsWithQuantities
  has_many :exposures, as: :view, dependent: :destroy,
    class_name: 'Exposure', extend: BodyTracking::TogglableExposures
  has_many :quantities, -> { order "lft" }, through: :exposures

  accepts_nested_attributes_for :targets, allow_destroy: true,
    reject_if: proc { |attrs|
      attrs[:quantity_id].blank? &&
        attrs[:thresholds_attributes].all? { |t| t[:value].blank? }
    }
  include Validations::NestedUniqueness
  validates_nested_uniqueness_for :targets,
    :effective_from, :quantity_id, :item_type, :item_id, :scope,
    scope: [:effective_from]

  validates :is_binding, uniqueness: {scope: :project_id}, if: :is_binding?
  validates :name, presence: true, uniqueness: {scope: :project_id},
    exclusion: {in: [I18n.t('goals.binding.name')], unless: :is_binding?}

  after_initialize do
    if new_record?
      self.is_binding = false if self.is_binding.nil?
      self.targets.new if !self.is_binding && self.targets.empty?
    end
  end

  before_save do
    quantities << targets.map(&:quantity)[0..5] if exposures.empty?
  end

  before_destroy prepend: true do
    !is_binding?
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  layout 'body_tracking', except: :subthresholds
  menu_item :body_trackers
  helper :body_trackers

  include Finders

  before_action :find_project_by_project_id, only: [:index, :new, :create]
  before_action :find_goal, only: [:edit, :update, :destroy]
  before_action :authorize

  def index
    @goals = @project.goals
  end

  def new
    @goal = @project.goals.new
    @targets = @goal.targets
  end

  def create
    @goal = @project.goals.new(goal_params)
    if @goal.save
      flash.now[:notice] = 'Created new goal'
      @goals = @project.goals
    else
      @targets = @goal.targets
      render :new
    end
  end

  def edit
  end

  def update
    if @goal.update(params.require(:goal).permit(:name, :description))
      flash.now[:notice] = 'Updated goal'
      @goals = @project.goals
    else
      render :new
    end
  end

  def destroy
    # TODO
  end

  private

  def goal_params
    params.require(:goal).permit(
      :name,
      :description,
      targets_attributes:
      [
        :id,
        :quantity_id,
        :scope,
        :destroy,
        thresholds_attributes: [
          :id,
          :quantity_id,
          :value,
          :unit_id,
          :_destroy
        ]
      ]
    )
  end
end

app/views/goals/_form.html.erb
<%= error_messages_for @goal %>

<div class="box tabular">
  <p><%= goal_f.text_field :name, required: true, style: "width: 95%;" %></p>
  <p><%= goal_f.text_area :description, rows: 3, style: "width: 95%;" %></p>

  <hr style="width: 95%;">

  <%= render partial: 'targets/form', locals: {goal_f: goal_f} %>
</div>

app/views/goals/_index.html.erb
<% if @goals.any? %>
  <table id="goals" class="list odd-even">
    <thead>
      <tr>
        <th style="width:20%"><%= l(:field_name) %></th>
        <th><%= l(:field_description) %></th>
        <th style="width:5%"><%= l(:field_action) %></th>
      </tr>
    </thead>
    <tbody>
      <% @goals.each do |g| %>
        <tr id="goal-<%= g.id %>" class="goal">
          <td class="topleft unwrappable">
            <div style="float:left;">
              <%= checked_image g.is_binding %><%= link_to g.name, goal_targets_path(g) %>
            </div>
            <div style="float:right;">
              <%# TODO: display # of active targets/targeted quantities %>
              <small><%#= " (#{pluralize(m.readouts.size, 'readout')})" %></small>
            </div>
          </td>
          <td class="description ellipsible"><%= g.description %></td>
          <td class="right shrunk">
            <%= delete_link(g, {remote: true, data: {}}) unless g.is_binding %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/goals/_new_form.html.erb
<h2><%= t ".heading_new_goal" %></h2>

<%= labelled_form_for [@project, @goal], remote: true,
  html: {id: 'new-goal-form', name: 'new-goal-form'} do |goal_f| %>

  <%= render partial: 'goals/form', locals: {goal_f: goal_f} %>

  <div class="tabular">
    <p>
      <%= submit_tag l(:button_create) %>
      <%= link_to l(:button_cancel), "#",
        onclick: "$('#new-goal').empty(); return false;" %>
    </p>
  </div>
<% end %>
<hr>

app/views/goals/_show_form.html.erb
<%# FIXME: nie trzeba ustawiac goal_id, data-remote samo wysle %>
<%= goal_f.collection_select :id, @project.goals, :id, :name,
  {include_blank: false, required: true, label: :field_goal},
  autocomplete: 'off',
  onchange: "$.ajax({
               url: '#{goal_path(id: :goal_id)}'
                      .replace('goal_id', $('#target_goal_attributes_id').val()),
               dataType: 'script'
             });
             return false;" %>
<%= link_to l(:button_add), '#',
  onclick: "$.ajax({
              url: '#{edit_goal_path(id: :goal_id)}'
                     .replace('goal_id', $('#target_goal_attributes_id').val()),
              dataType: 'script'
            });
            return false;",
  class: 'icon icon-add' %>
<% if goal_f.object.description? %>
  <p style='white-space: pre-wrap;' ><%= goal_f.object.description %></p>
<% end %>

app/views/goals/create.js.erb
$('#new-goal').empty();
$('#goals').html('<%= j render partial: 'goals/index' %>');

app/views/goals/index.html.erb
<div class="contextual">
  <%= link_to_if User.current.allowed_to?(:manage_body_trackers, @project),
    t(".link_new_goal"), new_project_goal_path(@project),
    {remote: true, class: 'icon icon-add'} %>
</div>

<div id="new-goal">
</div>

<%= title t(".heading") %>
<div id='goals'>
  <%= render partial: 'goals/index' %>
</div>

app/views/goals/new.js.erb
$('#new-goal').html('<%= j render partial: 'goals/new_form' %>');

app/views/goals/show.js.erb
$('#goal-form').html('<%= j render partial: 'goals/show_form', locals: {goal: @goal} %>');
$('input#target_effective_from').prop('disabled', <%= @goal.is_binding? %>)