config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects, shallow: true do
  resources :body_trackers, only: [:index] do
    collection do
      post 'defaults'
    end
  end

  resources :goals, except: [:show]

  resources :ingredients, only: [] do
    member do
      post 'adjust/:adjustment', controller: :meals, action: :adjust, as: :adjust
    end
  end
  resources :meals, except: [:show] do
    member do
      get 'edit_notes'
      patch 'update_notes'
      post 'toggle_eaten'
    end
    collection do
      post 'toggle_exposure'
    end
  end

  resources :measurement_routines, only: [:show, :edit] do
    resources :readouts, only: [:index]
    post 'toggle_exposure', controller: :readouts
  end
  # TODO: nest measurements inside routines?
  resources :measurements, except: [:show] do
    resource :readouts, only: [:edit, :update]
    member do
      get 'retake'
    end
    collection do
      get 'filter'
    end
  end

  resources :foods, except: [:show] do
    member do
      post 'toggle'
    end
    collection do
      get 'nutrients'
      post 'toggle_exposure'
      get 'filter'
      get 'autocomplete'
      post 'import'
    end
  end
  resources :sources, only: [:index, :create, :destroy]
  resources :quantities, except: [:show] do
    member do
      get 'new_child'
      post 'create_child'
      post 'move/:direction', action: :move, as: :move
    end
    collection do
      get 'parents'
      get 'filter'
    end
  end
  resources :units, only: [:index, :create, :destroy]
end

resources :goals, only: [] do
  resources :targets, param: :date, except: [:update] do
    member do
      get 'reapply'
    end
  end
  resource :targets, only: [:update]
  post 'toggle_exposure', controller: :targets
end
get 'subthresholds', controller: :targets, action: :subthresholds, as: :subthresholds

app/views/layouts/_sidebar.html.erb
<h3><%= link_to t(".link_summary"), project_body_trackers_path(@project) %></h3>

<h3><%= link_to t(".link_measurements"), project_measurements_path(@project) %></h3>

<h3><%= t ".heading_diet" %></h3>
<ul>
  <li><%= link_to t(".link_meals"), project_meals_path(@project) %></li>
  <li>
    <%= link_to t(".link_foods"), project_foods_path(@project) %>
    /
    <%= link_to t(".link_nutrients"), nutrients_project_foods_path(@project) %>
  </li>
</ul>

<h3><%= t ".heading_common" %></h3>
<ul>
  <li>
    <%= link_to t(".link_targets"), goal_targets_path(@project.goals.binding) %>
    /
    <%= link_to t(".link_goals"), project_goals_path(@project) %>
  </li>
  <li><%= link_to t(".link_quantities"), project_quantities_path(@project) %></li>
  <li><%= link_to t(".link_units"), project_units_path(@project) %></li>
  <li><%= link_to t(".link_sources"), project_sources_path(@project) %></li>
  <% if User.current.allowed_to?(:manage_body_trackers, @project) %>
    <li>&nbsp</li>
    <li><p><%= link_to t(".link_defaults"), defaults_project_body_trackers_path(@project),
      method: :post, data: {confirm: t(".confirm_defaults")} %></li>
  <% end %>
</ul>

app/views/layouts/body_tracking.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'body_tracking', plugin: 'body_tracking' %>
<% end %>

<% content_for :sidebar do %>
  <%= render partial: 'layouts/sidebar' %>
<% end %>

<%= render template: "layouts/base" %>

app/views/layouts/body_tracking.js.erb
$('div[id^=flash_]').remove();
$('div[id=errorExplanation]').remove();
$('#content').prepend('<%= j render_flash_messages %>');
<%= yield %>
//$(document).prop('title', '<%= html_title %>');